FROM node:16-alpine

WORKDIR '/app'

COPY ./package.json ./

RUN npm config rm proxy 
RUN npm config rm https-proxy --tried removing npm proxy 

RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]